ohsu-comp-bio/compbio-galaxy-wrappers

- mutsig/Dockerfile
- oncotator/Dockerfile
> oncotator and mutsig docker files

- calc_fpkm/calc_fpkm.py
- calc_fpkm/calc_norm.py
N_mapped, N_noFeatures, etc. lines were not being skipped, "if" condition fixed to skip. Added try/except to exit when all counts are zero, prior code was erroring with ZeroDivisionError"
[master bbc215a] N_mapped, N_noFeatures, etc. lines were not being skipped, if condition fixed to skip. Added try/except to exit when all counts are zero, prior code was erroring with ZeroDivisionError
> calc_fpkm.py bug fixes

- fusion_annotation/generate_fusionanno_files.py
fusion annotation flag for filtering mitochondrial and ribosomal associated fusions
> filtering added

- bam-matcher/.shed.yml
- bam-matcher/bam-matcher.conf
- bam-matcher/bam-matcher.xml
- bam-matcher/tool-data/all_fasta.loc.sample
- bam-matcher/tool_data_table_conf.xml.sample
Galaxy tool for Bam Matcher for comparing two BAM files are from same source.
> Bam Matcher

- cnvkit/.shed.yml
- cnvkit/cnvkit_batch.xml
- cnvkit/tool-data/all_fasta.loc.sample
- cnvkit/tool-data/cnvkit_ref_cnn.loc.sample
- cnvkit/tool_data_table_conf.xml.sample
Added:
- .shed.yml
- tool-data/
- tool_data_table_conf.xml
Updated:
- cnvkit_batch.xml
> Finalize wrapper and prep for toolshed

- epic/.shed.yml
- epic/epic.xml
- epic/macros.xml
Added:
- new tool wrapper for EPIC
- macros file for with version and requirements
- tool data for mapping ensembl to hugo symbols
- .shed.yml file for toolshed
> Epic Tool Wrapper

- CNV_plotter/gtrellis_CNV_NT.R
- CNV_plotter/stpv3_CNV_grapher_NT.xml
Handle proper input format for tumor percent including empty input
> Tumor percent and seq dict handling

- nanostring/proc_norm.py
- nanostring/proc_norm.xml
- nanostring/ruv_mbc.R
- nanostring/ruv_mbc.xml
The process_nanostring was replaced with proc_norm.xml for consistency. The output normalized matrices were also numbered by processing step, helps clarify which is the final normalized matrix.
Add ruv_mbc processing which applies RUV processing and compares with the cohort of metastatic breast cancers. Add xml galaxy wrapper that didn't work on my test instance. Testing on exaclinical to see if output formatting is handled differently between different versions.
> Number output from proc_norm, ruv_mbc processing

- nanostring/proc_norm.py
- nanostring/proc_norm.xml
- nanostring/ruv_mbc.R
- nanostring/ruv_mbc.xml
proc_norm.py
* added function that avoids global variables
*  normalization now subtracts the IgG antibody, less of an impact because of IgG drift. Issue #51
* accommodates new antibody format which includes Ab antibody source and metadata
* debug -ctrl flag. writes header and sample attributes to a separate dictionary
* When ID flag in RCC has value will give a warning message, before collapsing them and writing to run_metric.txt
* fix log2, add 1 before logging. Issue #50
ruv_mbc.R
* add mean difference plot output as pdf
* add gray bars to MBC cohort comparison which shows the entire range of signal. Issue #52
ruv_mbc.xml and proc_norm.xml
* adjusted output naming
* adjusted for updates to processing outputs.
> Multiple updates to all files

- fusion_annotation/fusion_annotation.py
Math was not correct in old file for fetching the sequences.
Also updated the filter flag so main wasn't so redundant. It was getting annoying.
> Corrected sequences fetches for fusion annotation

- addCorrectedCopies.R
Fixed bug that would throw an "argument is of length zero" error when the first segment was irrelevant
> addCorrectedCopies bug fix

- kbmtl/.shed.yml
- ruvseq/.shed.yml
Add untested .shed.yml for toolshed integration that may or may not work
for kbmtl and ruvseq.
> added untested .shed.yml

- vt/vt_normalize.xml
Removed ref genome db filter from VT Normalize
> VT normalize filter removed

- star_fusion/star_fusion.xml
Changes associated with upgrading to star-fusion 1.10.0.
> Star fusion 1.10.0

- vcf_select/vcf_select.py
> vcf_select: add vcf format

- dsp_delta/dsp_delta.R
- dsp_delta/dsp_delta.xml
- dsp_runner/dsp_runner.R
- dsp_runner/dsp_runner.xml
dsp_runner -- antibody boxplots were cleaned up of unnecessary labels/legends and legibility 
dsp_delta -- added tabular output for pairwise deltas for easier interepretation
> Output formatting and aesthetics

- dsp_delta/dsp_delta.R
- dsp_delta/dsp_delta.xml
- dsp_runner/dsp_runner.R
- dsp_runner/dsp_runner.xml
- westgard/westgard.py
- westgard/westgard.xml
consolidates dsp_delta plots onto one output file. introduces environment update to include gridExtra package.
> update to dsp_delta v1.1.0 and westgard v1.2.0

- dsp_runner/dsp_runner.R
- dsp_runner/dsp_runner.xml
- westgard/westgard.py
- westgard/westgard.xml
re-arranged tables/plots in dsp_runner report and added cover sheet with basic job summary
> update dsp_runner to produce cover sheet

- dsp_runner/dsp_runner.R
- dsp_runner/dsp_runner.xml
add percentiles to antibody/segment table and updated error handling
> update dsp_runner v1.0.9

- dsp_runner/dsp_runner.R
- dsp_runner/dsp_runner.xml
1.0.9 - corrected percentiles bug and added additional quartile values
1.0.11 - change recursive batch reading to Falseand  write out antibody table as Excel file
1.0.12 - remove hardcoding for good_tma and path.ord // temporarily removed TMA count error check
1.1.0 - Add rank percentile and formatting changes to pdf
1.1.1 - added conditions to bypass percentile table generation if tumor or stroma segments are absent
1.1.2 - changed 'Exported dataset' to 1 when reading Excel sheets
> Update dsp_runner v1.1.2

- dsp_runner/dsp_runner.R
> Dsp runner 113

- gatk_germline_cnv/annotate/gatkCNVannotate.R
ensure only unique gene names are added to gene column
> BIO-620-check_for_duplicate_gene_names_in_cnv_output

- sample_metrics/sample_metrics.py
- sample_metrics/sample_metrics.xml
added QIAseq_XP_RNA_STP to sample_metrics.py and incremented to v0.8.11
> BIO-674-prepare_input_files_for_QIAseq_XP_RNA_STP

- cgd_tx_eff/src/edu/ohsu/compbio/annovar/annovar_parser.py
- cgd_tx_eff/src/edu/ohsu/compbio/txeff/util/refseq_to_ccds.py
- cgd_tx_eff/test/edu/ohsu/compbio/annovar/test_annovar_parser.py
All the test cases so far had exactly two exons. But I just found one that has three. So i have expanded the functionality to support two or more exons.
> BIO-675 - Parse new type of Annovar variant_function string

- dsp_delta/dsp_delta.R
- dsp_delta/dsp_delta.xml
Added if-else check to correct Sample ID labelling that may be swapped due to A-Z sorting after filtering
> Update dsp_delta v1.2.2

- annotate_vcf_with_gff/annotate_vcf_with_gff.py
- annotate_vcf_with_gff/annotate_vcf_with_gff.xml
Annotate VCFs with gene name in INFO field from reference GFF and optionally filter by genes of interest from specified ordered test
> Create annotate_vcf_with_gff tool

- sample_metrics/sample_metrics.py
- sample_metrics/sample_metrics.xml
Add class DragenMetrics to handle metrics data for IlluminaExome_V2_DRAGEN
> BIO-699-Bioinformatics_ingest_DRAGEN_metrics_in_sample_metrics
